### ISSUE TITLE
Is it possible to set an autoexec.sas file in dedicated directory?

### ISSUE THREAD

**Issue by yabwon** [sasjs/server#117]
Hi Team!

First of all: Great Product! I love it!

Is it possible to set an `autoexec.sas` file in dedicated directory?

All the best
Bart

**Comment by allanbowe** [comment]
Thanks @yabwon !

I think a user-specific auto-exec is a great idea.  This would need to be saved at backend so that it can be available across different browser sessions.

This is probably a good point to enable home directories for users.  Then, we can add the autoexec to the home dir, allowing the autoexec to be easily viewed and edited.

The implementation would therefore require:

- Creating a `/Users` top level directory under `SAS_PATH`
- When a new user (or the default desktop user) logs in for the first time, a subdirectory is created with their userid, eg `/Users/allan`
- An empty `/Users/allan/autoexec.sas` file is also created
- The SAS executor is updated with the following code injected into the code.sas program:  `%inc "$(SAS_PATH)/Users/$(USERID)/autoexec.sas";`

**Comment by saadjutt01** [comment]
With the latest(v0.3.2) version, you can set autoexec to `~/.sasjs-server/user-autoexec.sas ` in DESKTOP mode.
